### ISSUE TITLE
프로젝트 패키지 구조 변경

### ISSUE THREAD

**Issue by snwlee** [TDD-Study-Though-Young-Man/board-test-homework#2]
**제목**: 프로젝트 패키지 구조 변경 요청

**본문**:
현재 우리 프로젝트의 패키지 구조가 간단하지 않고 관리하기 어렵다는 문제점이 있습니다. 이에 따라 패키지 구조를 변경하여 더 효율적으로 관리하고 유지보수할 수 있도록 하려고 합니다.

**변경 사항**:
- 현재의 패키지 구조는 다음과 같습니다:
    ```
    com.member.homework
    ├── config
    ├── domain
    ├── dto
    └── repository
    ...
    ```
- 변경하고자 하는 패키지 구조는 다음과 같습니다:
    ```
    com.[팀명].[프로젝트명]
    ├── member
    │   ├── controller
    │   ├── domain
    │   └── dto
    ├── comment
    │   ├── controller
    │   ├── domain
    │   └── dto
    └── util
    ...
    ```
- 변경된 구조는 API 관련 클래스들을 별도의 패키지로 분리하여 관리하고, 도메인 모델을 보다 명확히 구분합니다.

**장점**:
- 더 명확한 패키지 구조로 인해 코드의 유지보수성이 향상될 것으로 기대됩니다.
- API와 도메인 모델을 구분함으로써 코드의 의도를 더욱 명확히 전달할 수 있습니다.

**Comment by ch4570** [comment]
너무 좋은 의견입니다!
이런 구조로 변경해서 PR 올려주시면 좋을 거 같아요:)

config 패키지도 하나 두면 좋을 거 같아요 🙇🏻‍♂️

**Comment by xpmxf4** [comment]
오우 좋습니다 아주 굿 아이디어 인데요

**Comment by snwlee** [comment]
> 너무 좋은 의견입니다!
> 
> 이런 구조로 변경해서 PR 올려주시면 좋을 거 같아요:)
> 
> 
> 
> config 패키지도 하나 두면 좋을 거 같아요 🙇🏻‍♂️

확인 감사합니다!
config 패키지도 추가하겠습니다. :)

**Comment by snwlee** [comment]
> 오우 좋습니다 아주 굿 아이디어 인데요

확인 감사드립니다! :)
