### ISSUE TITLE
테스트 명세 방법 변경 제의 

### ISSUE THREAD

**Issue by khmgobe** [TDD-Study-Though-Young-Man/board-test-homework#7]
안녕하세요. 테스트 수정 도중  기존의 명세와 다르게 작성하는 방법이 여러가지가 있을 것 같아 찾아본 뒤에 공유드립니다.

기존 : @DisplayName과 함수 명, 2 가지의 정보를 작성한다.
  장점 : 자세하게 명세할 수 있다.
  단점 : 명세 및 작명에 할애하는 시간이 커질 수 있다.

ex) @DisplayName("회원 수정 시 아이디는 필수값이다.")
    void modifyMemberWithOutId() 

변경 : 함수명을 한글 및  _(언더스코어)로 작성한다.
  장점 : 간략하고 직관적이다.
  단점 : 상대적으로 자세하진 못 하다.

ex) void 관리자는_전체_사용자를_모두_조회할_수_있다()

우테코 크루분들 테스트 작성하는 방식이 궁금해서 찾아보니 이렇게 되어있는 경우가 많아 아래의 참고 링크 첨부드립니다.

참고 링크 [https://github.com/iamjooon2/jwp-refactoring/commit/fc02d5c9a57510fc3f6acf9bcbc3194f594f161c](url)

**Comment by only-juun** [comment]
좋은 방법이라고 생각합니다.

기존 방식은 
DisplayName에 들어가는 내용과 함수의 이름이 중복이라고도 볼 수 있습니다.

제안 방식은
중복 내용도 줄어들고, 테스트를 돌린 결과 목록에서도 기존과 큰 차이가 없습니다.
![image](https://github.com/TDD-Study-Though-Young-Man/board-test-homework/assets/79013722/08dfcc67-cdad-4b9f-b416-675f9af00723)

**Comment by xpmxf4** [comment]
저는 적용해봐도 나쁘지는 않다라는 생각이 듭니다.
실제로 코드를 봤을 때도 더 가독성이 좋다고 생각이 들고요.

다만 언젠가 비즈니스가 확장이 되어 테스트 코드를 리팩토링 해야 하는 순간이 온다면
shift+shift 로 메서드를 찾으려고 할겁니다.

<img width="500" alt="image" src="https://github.com/TDD-Study-Though-Young-Man/board-test-homework/assets/68197907/d09ce972-bc94-4813-8303-c8e41231a69a">


이때 보통 함수의 이름으로 찾으려고 할 텐데,
이때 개발자가 한국어로 메서드 이름을 찾으려고 할까, 아니면 영어로 검색을 할까라는 고민이 들고
저는 개인적으로 후자에 좀 더 의견이 기울여져 있습니다.

**Comment by ch4570** [comment]
저도 좋은 의견이라고 생각합니다.
코틀린에서는 백틱을 걸어서 이미 저렇게 많이 사용하고 있습니다!

매우 동히합니다.

**Comment by featureofme** [comment]
다양한 고견 감사드립니다. @snwlee 님 의견까지 듣고 결정해보죠.

**Comment by snwlee** [comment]
저도 매우 동의 합니다.

김영한님께서도 한국인이랑 일하면 
테스트 코드에서는 한글로 메서드 작명을 하라고 
말씀 하셨습니다.

🙏

**Comment by xpmxf4** [comment]
> 저도 매우 동의 합니다.
> 
> 김영한님께서도 한국인이랑 일하면 테스트 코드에서는 한글로 메서드 작명을 하라고 말씀 하셨습니다.
> 
> 🙏

오호...?
