### ISSUE TITLE
Test Util 클래스 에서의 팩토리 메서드 이동

### ISSUE THREAD

**Issue by xpmxf4** [TDD-Study-Though-Young-Man/board-test-homework#8]
https://github.com/TDD-Study-Though-Young-Man/board-test-homework/blob/002f15be0aac96ddd6a31e64324b3ec8d8fbea8b/src/test/java/com/member/homework/util/TestUtil.java#L33C5-L44C6

여기에 모두가 유틸용 엔티티 생성 메서드를 넣게 되면 또 하나의 관리 비용이라고 생각합니다.
오버로딩 특성상 파라미터로 들어오는 자료형으로만 따지기 때문에, 수 많은 생성자가 들어올거라
사용한 테스트 클래스 내로 가는 게 더 좋다고 생각합니다.

**Comment by ch4570** [comment]
좋은 생각입니다:)
저도 TestUtil 만들고 겁나게 후회했습니다.

Util 클래스보다는 각 클래스에 위치 시키되, 추후 fixtureMonkey와 같은 라이브러리로 조금 더 좋은
코드를 작성할 수 있을거라 기대합니다.

**Comment by featureofme** [comment]
좋은 생각입니다~ 엄지척!
